# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d765383f5223d0e5e0925b3b36c3b45abd92ee7f16f4306e6b23ec9515cf6105e16a547daccb76c2296937cfb4183cfa01474e65dd8c0a4ae558997750e892f2

test:
  secret_key_base: c4b9cde0ab8d51c0869b6d5ac87441550d8634b3d1761dc2bcf3a473217c673e2c6fc67838835b91c59926c7d9d60c42e5aa163c8d72be1f848af27bd071abd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
